/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\liao.kailun\\Desktop\\New folder (2)\\markdownblog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-dee70954",
    path: "/Components/Echarts/echarts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dee70954").then(next)
    },
  },
  {
    name: "v-118a0748",
    path: "/Components/MiniPrograme/package.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-118a0748").then(next)
    },
  },
  {
    name: "v-7d90b73c",
    path: "/Components/CpNet/base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d90b73c").then(next)
    },
  },
  {
    name: "v-668422b0",
    path: "/Components/MiniPrograme/delay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-668422b0").then(next)
    },
  },
  {
    name: "v-32e28668",
    path: "/Components/NodeJs/Start.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32e28668").then(next)
    },
  },
  {
    name: "v-be9653d4",
    path: "/Components/MiniPrograme/base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-be9653d4").then(next)
    },
  },
  {
    name: "v-69a880da",
    path: "/Components/NodeJs/Node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69a880da").then(next)
    },
  },
  {
    name: "v-580a4394",
    path: "/Components/WebPack/LoaderAndPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-580a4394").then(next)
    },
  },
  {
    name: "v-729ac2da",
    path: "/Components/WebPack/TreeShaking.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-729ac2da").then(next)
    },
  },
  {
    name: "v-31c46882",
    path: "/Components/WebPack/WebPackDevServer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31c46882").then(next)
    },
  },
  {
    name: "v-49887862",
    path: "/Components/WebPack/sourcemap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49887862").then(next)
    },
  },
  {
    name: "v-6565f56c",
    path: "/Components/WebPack/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6565f56c").then(next)
    },
  },
  {
    name: "v-3734d1f0",
    path: "/Components/base/MapAndSet.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3734d1f0").then(next)
    },
  },
  {
    name: "v-5168da28",
    path: "/Components/base/Reg.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5168da28").then(next)
    },
  },
  {
    name: "v-5948fc08",
    path: "/Components/base/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5948fc08").then(next)
    },
  },
  {
    name: "v-1ed84da8",
    path: "/Components/base/start.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ed84da8").then(next)
    },
  },
  {
    name: "v-27019a42",
    path: "/Components/dataStructureAndCount/StackAndHeap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27019a42").then(next)
    },
  },
  {
    name: "v-30b9ade2",
    path: "/Components/dataStructureAndCount/DoCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30b9ade2").then(next)
    },
  },
  {
    name: "v-33a06ec4",
    path: "/Components/dataStructureAndCount/count.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33a06ec4").then(next)
    },
  },
  {
    name: "v-242e3c70",
    path: "/Components/htmlcss/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-242e3c70").then(next)
    },
  },
  {
    name: "v-7fad3f62",
    path: "/Components/htmlcss/Flex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fad3f62").then(next)
    },
  },
  {
    name: "v-e4c77034",
    path: "/Components/htmlcss/FontCss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4c77034").then(next)
    },
  },
  {
    name: "v-221898bc",
    path: "/Components/htmlcss/Selector.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-221898bc").then(next)
    },
  },
  {
    name: "v-60ad81f4",
    path: "/Components/htmlcss/animation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60ad81f4").then(next)
    },
  },
  {
    name: "v-738ea9e8",
    path: "/Components/javascript/AST.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-738ea9e8").then(next)
    },
  },
  {
    name: "v-57833188",
    path: "/Components/javascript/Array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57833188").then(next)
    },
  },
  {
    name: "v-7eb0eba8",
    path: "/Components/javascript/TypeError.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7eb0eba8").then(next)
    },
  },
  {
    name: "v-b0e78630",
    path: "/Components/javascript/ESsix.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0e78630").then(next)
    },
  },
  {
    name: "v-1c79e368",
    path: "/Components/javascript/RecursionTree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c79e368").then(next)
    },
  },
  {
    name: "v-553ac608",
    path: "/Components/javascript/clone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-553ac608").then(next)
    },
  },
  {
    name: "v-5a19bdc0",
    path: "/Components/javascript/base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a19bdc0").then(next)
    },
  },
  {
    name: "v-3130f0e0",
    path: "/Components/javascript/designPatterns.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3130f0e0").then(next)
    },
  },
  {
    name: "v-45f51488",
    path: "/Components/javascript/extends.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45f51488").then(next)
    },
  },
  {
    name: "v-f02bda70",
    path: "/Components/md_interview/Interview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f02bda70").then(next)
    },
  },
  {
    name: "v-ade7a7b0",
    path: "/Components/javascript/fileUpload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ade7a7b0").then(next)
    },
  },
  {
    name: "v-4f7a0fd8",
    path: "/Components/md_view/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f7a0fd8").then(next)
    },
  },
  {
    name: "v-0ec807b4",
    path: "/Components/performance/BorserPerformance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ec807b4").then(next)
    },
  },
  {
    name: "v-3487cc0e",
    path: "/Components/performance/Browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3487cc0e").then(next)
    },
  },
  {
    name: "v-49d307fe",
    path: "/Components/performance/Performance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49d307fe").then(next)
    },
  },
  {
    name: "v-bb20220c",
    path: "/Components/performance/WebWorker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb20220c").then(next)
    },
  },
  {
    name: "v-6b4b15d4",
    path: "/Components/react/ReactPerfomance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b4b15d4").then(next)
    },
  },
  {
    name: "v-3283f1c2",
    path: "/Components/react/Reacthooks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3283f1c2").then(next)
    },
  },
  {
    name: "v-c4d5817c",
    path: "/Components/react/base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4d5817c").then(next)
    },
  },
  {
    name: "v-7b1a1b00",
    path: "/Components/static/Button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b1a1b00").then(next)
    },
  },
  {
    name: "v-415c1e1c",
    path: "/Components/static/GuaguaLe.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-415c1e1c").then(next)
    },
  },
  {
    name: "v-84328e1c",
    path: "/Components/static/Icon.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84328e1c").then(next)
    },
  },
  {
    name: "v-d504b7f0",
    path: "/Components/static/IconStyle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d504b7f0").then(next)
    },
  },
  {
    name: "v-d562572c",
    path: "/Components/static/LuckyRolling.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d562572c").then(next)
    },
  },
  {
    name: "v-2e8f0328",
    path: "/Components/static/MagnifyingGlass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e8f0328").then(next)
    },
  },
  {
    name: "v-4d070ab0",
    path: "/Components/static/Message.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d070ab0").then(next)
    },
  },
  {
    name: "v-b35c4f70",
    path: "/Components/static/Pinterest.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b35c4f70").then(next)
    },
  },
  {
    name: "v-1aced8c8",
    path: "/Components/static/SlideVerify.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1aced8c8").then(next)
    },
  },
  {
    name: "v-0d994ec6",
    path: "/Components/vue/Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d994ec6").then(next)
    },
  },
  {
    name: "v-b954e374",
    path: "/Components/vue/FirstLoad.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b954e374").then(next)
    },
  },
  {
    name: "v-f40bc0fc",
    path: "/Components/vue/Vuethree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f40bc0fc").then(next)
    },
  },
  {
    name: "v-44a85ebc",
    path: "/Components/vue/base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44a85ebc").then(next)
    },
  },
  {
    name: "v-acdf3fbc",
    path: "/Components/vue/code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-acdf3fbc").then(next)
    },
  },
  {
    name: "v-40ea6b94",
    path: "/Components/vue/directive.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40ea6b94").then(next)
    },
  },
  {
    name: "v-2a433f5a",
    path: "/Components/vue/innerComponents.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a433f5a").then(next)
    },
  },
  {
    name: "v-7368b5a0",
    path: "/Components/vue/mixin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7368b5a0").then(next)
    },
  },
  {
    name: "v-15bd0256",
    path: "/Components/vue/permissionControl.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15bd0256").then(next)
    },
  },
  {
    name: "v-4bb298c2",
    path: "/Components/vue/template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bb298c2").then(next)
    },
  },
  {
    name: "v-19e209c2",
    path: "/Components/vue/vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19e209c2").then(next)
    },
  },
  {
    name: "v-d781a7b0",
    path: "/Components/work/SendeCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d781a7b0").then(next)
    },
  },
  {
    name: "v-6ccc2e30",
    path: "/Components/work/Scan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ccc2e30").then(next)
    },
  },
  {
    name: "v-03d05308",
    path: "/Components/work/WebSocket.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03d05308").then(next)
    },
  },
  {
    name: "v-5ced1930",
    path: "/Components/work/debAndThr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ced1930").then(next)
    },
  },
  {
    name: "v-3b12fbda",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b12fbda").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]