/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "芒梨博客",
  "description": "个人博客",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "计算机网络基础知识总结",
      "frontmatter": {},
      "regularPath": "/Components/cp_netservice/cpnetservice.html",
      "relativePath": "Components/cp_netservice/cpnetservice.md",
      "key": "v-20454bbc",
      "path": "/Components/cp_netservice/cpnetservice.html",
      "headers": [
        {
          "level": 2,
          "title": "网络层次划分",
          "slug": "网络层次划分"
        },
        {
          "level": 3,
          "title": "物理层",
          "slug": "物理层"
        },
        {
          "level": 3,
          "title": "数据链路层",
          "slug": "数据链路层"
        },
        {
          "level": 3,
          "title": "网络层",
          "slug": "网络层"
        },
        {
          "level": 3,
          "title": "传输层",
          "slug": "传输层"
        },
        {
          "level": 3,
          "title": "会话层",
          "slug": "会话层"
        },
        {
          "level": 3,
          "title": "表示层",
          "slug": "表示层"
        },
        {
          "level": 3,
          "title": "应用层",
          "slug": "应用层"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/Components/md_interview/Interview.html",
      "relativePath": "Components/md_interview/Interview.md",
      "key": "v-f02bda70",
      "path": "/Components/md_interview/Interview.html"
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/Components/md_view/vue.html",
      "relativePath": "Components/md_view/vue.md",
      "key": "v-4f7a0fd8",
      "path": "/Components/md_view/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "（1）什么是vue生命周期?",
          "slug": "_1-什么是vue生命周期"
        },
        {
          "level": 3,
          "title": "（2）vue生命周期的作用是什么?",
          "slug": "_2-vue生命周期的作用是什么"
        },
        {
          "level": 3,
          "title": "（3）vue生命周期总共有几个阶段?",
          "slug": "_3-vue生命周期总共有几个阶段"
        },
        {
          "level": 3,
          "title": "（4）第一次页面加载会触发哪几个钩子?",
          "slug": "_4-第一次页面加载会触发哪几个钩子"
        },
        {
          "level": 3,
          "title": "（5）DOM 渲染在 哪个周期中就已经完成?",
          "slug": "_5-dom-渲染在-哪个周期中就已经完成"
        },
        {
          "level": 3,
          "title": "（6）简单描述每个周期具体适合哪些场景?",
          "slug": "_6-简单描述每个周期具体适合哪些场景"
        },
        {
          "level": 2,
          "title": "axios的方法和请求响应数据结构",
          "slug": "axios的方法和请求响应数据结构"
        },
        {
          "level": 3,
          "title": "请求方法别名",
          "slug": "请求方法别名"
        },
        {
          "level": 3,
          "title": "相应数据结构",
          "slug": "相应数据结构"
        },
        {
          "level": 2,
          "title": "在VUE中封装axios",
          "slug": "在vue中封装axios"
        },
        {
          "level": 3,
          "title": "请求响应之then  catch",
          "slug": "请求响应之then-catch"
        },
        {
          "level": 2,
          "title": "Vuex状态管理",
          "slug": "vuex状态管理"
        },
        {
          "level": 2,
          "title": "VUE中router的钩子函数",
          "slug": "vue中router的钩子函数"
        },
        {
          "level": 2,
          "title": "ES6的基本知识",
          "slug": "es6的基本知识"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 2,
          "title": "vue store存储commit和dispatch",
          "slug": "vue-store存储commit和dispatch"
        },
        {
          "level": 2,
          "title": "vue  路由导航",
          "slug": "vue-路由导航"
        },
        {
          "level": 2,
          "title": "vue中computed和method 区别",
          "slug": "vue中computed和method-区别"
        }
      ]
    },
    {
      "title": "JavaScript 的常用方法",
      "frontmatter": {},
      "regularPath": "/Components/js_docs/JS.html",
      "relativePath": "Components/js_docs/JS.md",
      "key": "v-7392b3c2",
      "path": "/Components/js_docs/JS.html",
      "headers": [
        {
          "level": 2,
          "title": "一、String类型",
          "slug": "一、string类型"
        },
        {
          "level": 3,
          "title": "1.charAt",
          "slug": "_1-charat"
        },
        {
          "level": 3,
          "title": "2.chartCodeAt()",
          "slug": "_2-chartcodeat"
        },
        {
          "level": 3,
          "title": "3.concat()",
          "slug": "_3-concat"
        },
        {
          "level": 3,
          "title": "4.indexOf()",
          "slug": "_4-indexof"
        },
        {
          "level": 3,
          "title": "5.match()",
          "slug": "_5-match"
        },
        {
          "level": 3,
          "title": "6.replace()",
          "slug": "_6-replace"
        },
        {
          "level": 3,
          "title": "7.search():",
          "slug": "_7-search"
        },
        {
          "level": 3,
          "title": "8.slice()",
          "slug": "_8-slice"
        },
        {
          "level": 3,
          "title": "9.split():",
          "slug": "_9-split"
        },
        {
          "level": 3,
          "title": "10.toLocaleLowerCase()",
          "slug": "_10-tolocalelowercase"
        },
        {
          "level": 3,
          "title": "11.toLocaleUpperCase()",
          "slug": "_11-tolocaleuppercase"
        },
        {
          "level": 3,
          "title": "12.substr()",
          "slug": "_12-substr"
        },
        {
          "level": 3,
          "title": "13.subString()",
          "slug": "_13-substring"
        },
        {
          "level": 2,
          "title": "二、数组 Array",
          "slug": "二、数组-array"
        },
        {
          "level": 3,
          "title": "1.slice[start,end]",
          "slug": "_1-slice-start-end"
        },
        {
          "level": 3,
          "title": "2.splice():",
          "slug": "_2-splice"
        },
        {
          "level": 3,
          "title": "3.pop()",
          "slug": "_3-pop"
        },
        {
          "level": 3,
          "title": "4.push()",
          "slug": "_4-push"
        },
        {
          "level": 3,
          "title": "5.shift()",
          "slug": "_5-shift"
        },
        {
          "level": 3,
          "title": "6.unshift()",
          "slug": "_6-unshift"
        },
        {
          "level": 3,
          "title": "7.sort()",
          "slug": "_7-sort"
        },
        {
          "level": 3,
          "title": "8.concat(3,4)",
          "slug": "_8-concat-3-4"
        },
        {
          "level": 3,
          "title": "9.join()",
          "slug": "_9-join"
        },
        {
          "level": 3,
          "title": "10.indexOf()",
          "slug": "_10-indexof"
        },
        {
          "level": 3,
          "title": "11.foeEach()",
          "slug": "_11-foeeach"
        },
        {
          "level": 3,
          "title": "12.map",
          "slug": "_12-map"
        },
        {
          "level": 3,
          "title": "13.for in",
          "slug": "_13-for-in"
        },
        {
          "level": 2,
          "title": "三、ES5-every和some方法：",
          "slug": "三、es5-every和some方法"
        },
        {
          "level": 3,
          "title": "1.every",
          "slug": "_1-every"
        },
        {
          "level": 3,
          "title": "2.some",
          "slug": "_2-some"
        },
        {
          "level": 3,
          "title": "3.Array.isArray(obj)",
          "slug": "_3-array-isarray-obj"
        },
        {
          "level": 3,
          "title": "4.filter(function(element))",
          "slug": "_4-filter-function-element"
        },
        {
          "level": 3,
          "title": "5.reduce or reduceRight",
          "slug": "_5-reduce-or-reduceright"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201805%2F19%2F20180519142022_kVASd.thumb.700_0.jpeg&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1664607012&t=d9c7f089d193df41489bad49ebf22dc3",
        "heroText": "karry的学习日记",
        "tagline": "没有跨不过去的坎，只有走不完的路",
        "features": [
          {
            "title": "梦想-最开始的地方",
            "details": "活成自己最想活成的样子，加油！"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b12fbda",
      "path": "/"
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "logo": "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F201911%2F30%2F20191130103938_uNhF5.thumb.700_0.jpeg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1664606884&t=978883c3b180812cc76c793f1f6a6b92",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "JS",
        "link": "/Components/js_docs/JS"
      },
      {
        "text": "Vue",
        "link": "/Components/md_view/vue"
      },
      {
        "text": "计算机网络知识",
        "link": "/Components/cp_netservice/cpnetservice"
      },
      {
        "text": "面试总结",
        "link": "/Components/md_interview/interview"
      },
      {
        "text": "2021",
        "ariLabel": "2021",
        "items": [
          {
            "text": "May",
            "link": "/2020/5/"
          },
          {
            "text": "June",
            "link": "/2020/6/"
          }
        ]
      },
      {
        "text": "github",
        "link": ""
      }
    ],
    "sidebar": {
      "/Components/": [
        {
          "title": "开发指南",
          "collapsable": false,
          "children": []
        },
        {
          "title": "静态组件",
          "collapsable": false,
          "children": []
        },
        {
          "title": "动态组件",
          "collapsable": false,
          "children": []
        }
      ]
    }
  }
}