/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "芒梨博客",
  "description": "个人博客",
  "base": "/studyblog.github.io/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/studyblog.github.io/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "计算机网络基础知识总结",
      "frontmatter": {},
      "regularPath": "/Components/CpNet/base.html",
      "relativePath": "Components/CpNet/base.md",
      "key": "v-7d90b73c",
      "path": "/Components/CpNet/base.html",
      "headers": [
        {
          "level": 2,
          "title": "网络层次划分",
          "slug": "网络层次划分"
        },
        {
          "level": 3,
          "title": "物理层",
          "slug": "物理层"
        },
        {
          "level": 3,
          "title": "数据链路层",
          "slug": "数据链路层"
        },
        {
          "level": 3,
          "title": "网络层",
          "slug": "网络层"
        },
        {
          "level": 3,
          "title": "传输层",
          "slug": "传输层"
        },
        {
          "level": 3,
          "title": "会话层",
          "slug": "会话层"
        },
        {
          "level": 3,
          "title": "表示层",
          "slug": "表示层"
        },
        {
          "level": 3,
          "title": "应用层",
          "slug": "应用层"
        }
      ]
    },
    {
      "title": "MiniPrograme",
      "frontmatter": {},
      "regularPath": "/Components/MiniPrograme/base.html",
      "relativePath": "Components/MiniPrograme/base.md",
      "key": "v-be9653d4",
      "path": "/Components/MiniPrograme/base.html",
      "headers": [
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 2,
          "title": "钩子函数",
          "slug": "钩子函数"
        }
      ]
    },
    {
      "title": "创建第一个应用",
      "frontmatter": {},
      "regularPath": "/Components/NodeJs/Start.html",
      "relativePath": "Components/NodeJs/Start.md",
      "key": "v-32e28668",
      "path": "/Components/NodeJs/Start.html",
      "headers": [
        {
          "level": 2,
          "title": "创建第一个应用",
          "slug": "创建第一个应用"
        },
        {
          "level": 2,
          "title": "Node包管理工具-npm",
          "slug": "node包管理工具-npm"
        },
        {
          "level": 2,
          "title": "Node.js REPL(交互式解析器)",
          "slug": "node-js-repl-交互式解析器"
        },
        {
          "level": 2,
          "title": "Node.js回调函数",
          "slug": "node-js回调函数"
        },
        {
          "level": 2,
          "title": "Node.js事件循环",
          "slug": "node-js事件循环"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/Components/base/introduce.html",
      "relativePath": "Components/base/introduce.md",
      "key": "v-5948fc08",
      "path": "/Components/base/introduce.html"
    },
    {
      "title": "找出出现次数最多的字符",
      "frontmatter": {},
      "regularPath": "/Components/dataStructureAndCount/count.html",
      "relativePath": "Components/dataStructureAndCount/count.md",
      "key": "v-33a06ec4",
      "path": "/Components/dataStructureAndCount/count.html",
      "headers": [
        {
          "level": 2,
          "title": "找出出现次数最多的字符",
          "slug": "找出出现次数最多的字符"
        },
        {
          "level": 2,
          "title": "null与undefined",
          "slug": "null与undefined"
        }
      ]
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/Components/base/start.html",
      "relativePath": "Components/base/start.md",
      "key": "v-1ed84da8",
      "path": "/Components/base/start.html",
      "headers": [
        {
          "level": 2,
          "title": "获取组件",
          "slug": "获取组件"
        },
        {
          "level": 2,
          "title": "引入组件",
          "slug": "引入组件"
        },
        {
          "level": 2,
          "title": "使用组件",
          "slug": "使用组件"
        }
      ]
    },
    {
      "title": "一、Flex布局表示弹性布局，为盒模型提供最大灵活性。",
      "frontmatter": {},
      "regularPath": "/Components/htmlcss/Flex.html",
      "relativePath": "Components/htmlcss/Flex.md",
      "key": "v-7fad3f62",
      "path": "/Components/htmlcss/Flex.html",
      "headers": [
        {
          "level": 2,
          "title": "一、Flex布局表示弹性布局，为盒模型提供最大灵活性。",
          "slug": "一、flex布局表示弹性布局-为盒模型提供最大灵活性。"
        },
        {
          "level": 2,
          "title": "二、flex 容器的一些属性",
          "slug": "二、flex-容器的一些属性"
        },
        {
          "level": 3,
          "title": "1.flex-direction",
          "slug": "_1-flex-direction"
        },
        {
          "level": 3,
          "title": "2.flex-wrap",
          "slug": "_2-flex-wrap"
        },
        {
          "level": 3,
          "title": "3.flex-flow",
          "slug": "_3-flex-flow"
        },
        {
          "level": 3,
          "title": "4.justify-content",
          "slug": "_4-justify-content"
        },
        {
          "level": 3,
          "title": "5.align-items",
          "slug": "_5-align-items"
        },
        {
          "level": 3,
          "title": "6.align-content",
          "slug": "_6-align-content"
        },
        {
          "level": 3,
          "title": "7.order 属性",
          "slug": "_7-order-属性"
        },
        {
          "level": 3,
          "title": "8.flex-grow 属性",
          "slug": "_8-flex-grow-属性"
        },
        {
          "level": 3,
          "title": "9.flex-shrink 属性",
          "slug": "_9-flex-shrink-属性"
        },
        {
          "level": 3,
          "title": "10.flex-basis",
          "slug": "_10-flex-basis"
        },
        {
          "level": 3,
          "title": "11.flex",
          "slug": "_11-flex"
        },
        {
          "level": 3,
          "title": "12.align-self属性",
          "slug": "_12-align-self属性"
        }
      ]
    },
    {
      "title": "var、let、const",
      "frontmatter": {},
      "regularPath": "/Components/javascript/ESsix.html",
      "relativePath": "Components/javascript/ESsix.md",
      "key": "v-b0e78630",
      "path": "/Components/javascript/ESsix.html",
      "headers": [
        {
          "level": 2,
          "title": "var、let、const",
          "slug": "var、let、const"
        },
        {
          "level": 2,
          "title": "数组篇",
          "slug": "数组篇"
        },
        {
          "level": 2,
          "title": "实例对象新增的方法",
          "slug": "实例对象新增的方法"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/Components/NodeJs/Node.html",
      "relativePath": "Components/NodeJs/Node.md",
      "key": "v-69a880da",
      "path": "/Components/NodeJs/Node.html"
    },
    {
      "title": "JavaScript 的常用方法",
      "frontmatter": {},
      "regularPath": "/Components/javascript/base.html",
      "relativePath": "Components/javascript/base.md",
      "key": "v-5a19bdc0",
      "path": "/Components/javascript/base.html",
      "headers": [
        {
          "level": 2,
          "title": "一、String类型",
          "slug": "一、string类型"
        },
        {
          "level": 3,
          "title": "1.charAt",
          "slug": "_1-charat"
        },
        {
          "level": 3,
          "title": "2.chartCodeAt()",
          "slug": "_2-chartcodeat"
        },
        {
          "level": 3,
          "title": "3.concat()",
          "slug": "_3-concat"
        },
        {
          "level": 3,
          "title": "4.indexOf()",
          "slug": "_4-indexof"
        },
        {
          "level": 3,
          "title": "5.match()",
          "slug": "_5-match"
        },
        {
          "level": 3,
          "title": "6.replace()",
          "slug": "_6-replace"
        },
        {
          "level": 3,
          "title": "7.search():",
          "slug": "_7-search"
        },
        {
          "level": 3,
          "title": "8.slice()",
          "slug": "_8-slice"
        },
        {
          "level": 3,
          "title": "9.split():",
          "slug": "_9-split"
        },
        {
          "level": 3,
          "title": "10.toLocaleLowerCase()",
          "slug": "_10-tolocalelowercase"
        },
        {
          "level": 3,
          "title": "11.toLocaleUpperCase()",
          "slug": "_11-tolocaleuppercase"
        },
        {
          "level": 3,
          "title": "12.substr()",
          "slug": "_12-substr"
        },
        {
          "level": 3,
          "title": "13.subString()",
          "slug": "_13-substring"
        },
        {
          "level": 2,
          "title": "二、数组 Array",
          "slug": "二、数组-array"
        },
        {
          "level": 3,
          "title": "1.slice[start,end]",
          "slug": "_1-slice-start-end"
        },
        {
          "level": 3,
          "title": "2.splice():",
          "slug": "_2-splice"
        },
        {
          "level": 3,
          "title": "3.pop()",
          "slug": "_3-pop"
        },
        {
          "level": 3,
          "title": "4.push()",
          "slug": "_4-push"
        },
        {
          "level": 3,
          "title": "5.shift()",
          "slug": "_5-shift"
        },
        {
          "level": 3,
          "title": "6.unshift()",
          "slug": "_6-unshift"
        },
        {
          "level": 3,
          "title": "7.sort()",
          "slug": "_7-sort"
        },
        {
          "level": 3,
          "title": "8.concat(3,4)",
          "slug": "_8-concat-3-4"
        },
        {
          "level": 3,
          "title": "9.join()",
          "slug": "_9-join"
        },
        {
          "level": 3,
          "title": "10.indexOf()",
          "slug": "_10-indexof"
        },
        {
          "level": 3,
          "title": "11.foeEach()",
          "slug": "_11-foeeach"
        },
        {
          "level": 3,
          "title": "12.map",
          "slug": "_12-map"
        },
        {
          "level": 3,
          "title": "13.for in",
          "slug": "_13-for-in"
        },
        {
          "level": 2,
          "title": "三、ES5-every和some方法：",
          "slug": "三、es5-every和some方法"
        },
        {
          "level": 3,
          "title": "1.every",
          "slug": "_1-every"
        },
        {
          "level": 3,
          "title": "2.some",
          "slug": "_2-some"
        },
        {
          "level": 3,
          "title": "3.Array.isArray(obj)",
          "slug": "_3-array-isarray-obj"
        },
        {
          "level": 3,
          "title": "4.filter(function(element))",
          "slug": "_4-filter-function-element"
        },
        {
          "level": 3,
          "title": "5.reduce or reduceRight",
          "slug": "_5-reduce-or-reduceright"
        }
      ]
    },
    {
      "title": "Font样式",
      "frontmatter": {},
      "regularPath": "/Components/htmlcss/FontCss.html",
      "relativePath": "Components/htmlcss/FontCss.md",
      "key": "v-e4c77034",
      "path": "/Components/htmlcss/FontCss.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        }
      ]
    },
    {
      "title": "工厂模式",
      "frontmatter": {},
      "regularPath": "/Components/javascript/designPatterns.html",
      "relativePath": "Components/javascript/designPatterns.md",
      "key": "v-3130f0e0",
      "path": "/Components/javascript/designPatterns.html",
      "headers": [
        {
          "level": 2,
          "title": "工厂模式",
          "slug": "工厂模式"
        },
        {
          "level": 2,
          "title": "单例模式",
          "slug": "单例模式"
        },
        {
          "level": 2,
          "title": "代理模式",
          "slug": "代理模式"
        },
        {
          "level": 2,
          "title": "职责链模式",
          "slug": "职责链模式"
        },
        {
          "level": 2,
          "title": "装饰者模式",
          "slug": "装饰者模式"
        },
        {
          "level": 2,
          "title": "观察者模式",
          "slug": "观察者模式"
        },
        {
          "level": 2,
          "title": "发布订阅模式",
          "slug": "发布订阅模式"
        }
      ]
    },
    {
      "title": "一. 如何获取浏览器URL中查询字符串中的参数？",
      "frontmatter": {},
      "regularPath": "/Components/javascript/extends.html",
      "relativePath": "Components/javascript/extends.md",
      "key": "v-45f51488",
      "path": "/Components/javascript/extends.html",
      "headers": [
        {
          "level": 2,
          "title": "一. 如何获取浏览器URL中查询字符串中的参数？",
          "slug": "一-如何获取浏览器url中查询字符串中的参数"
        },
        {
          "level": 2,
          "title": "二. js实现一个打点计时器",
          "slug": "二-js实现一个打点计时器"
        },
        {
          "level": 3,
          "title": "setTimeout方法",
          "slug": "settimeout方法"
        },
        {
          "level": 3,
          "title": "setInterval()方法",
          "slug": "setinterval-方法"
        },
        {
          "level": 2,
          "title": "三. 用js实现一个标准的排序算法",
          "slug": "三-用js实现一个标准的排序算法"
        },
        {
          "level": 3,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/Components/md_view/vue.html",
      "relativePath": "Components/md_view/vue.md",
      "key": "v-4f7a0fd8",
      "path": "/Components/md_view/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "（1）什么是vue生命周期?",
          "slug": "_1-什么是vue生命周期"
        },
        {
          "level": 3,
          "title": "（2）vue生命周期的作用是什么?",
          "slug": "_2-vue生命周期的作用是什么"
        },
        {
          "level": 3,
          "title": "（3）vue生命周期总共有几个阶段?",
          "slug": "_3-vue生命周期总共有几个阶段"
        },
        {
          "level": 3,
          "title": "（4）第一次页面加载会触发哪几个钩子?",
          "slug": "_4-第一次页面加载会触发哪几个钩子"
        },
        {
          "level": 3,
          "title": "（5）DOM 渲染在 哪个周期中就已经完成?",
          "slug": "_5-dom-渲染在-哪个周期中就已经完成"
        },
        {
          "level": 3,
          "title": "（6）简单描述每个周期具体适合哪些场景?",
          "slug": "_6-简单描述每个周期具体适合哪些场景"
        },
        {
          "level": 2,
          "title": "axios的方法和请求响应数据结构",
          "slug": "axios的方法和请求响应数据结构"
        },
        {
          "level": 3,
          "title": "请求方法别名",
          "slug": "请求方法别名"
        },
        {
          "level": 3,
          "title": "相应数据结构",
          "slug": "相应数据结构"
        },
        {
          "level": 2,
          "title": "在VUE中封装axios",
          "slug": "在vue中封装axios"
        },
        {
          "level": 3,
          "title": "请求响应之then  catch",
          "slug": "请求响应之then-catch"
        },
        {
          "level": 2,
          "title": "Vuex状态管理",
          "slug": "vuex状态管理"
        },
        {
          "level": 2,
          "title": "VUE中router的钩子函数",
          "slug": "vue中router的钩子函数"
        },
        {
          "level": 2,
          "title": "ES6的基本知识",
          "slug": "es6的基本知识"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 2,
          "title": "vue store存储commit和dispatch",
          "slug": "vue-store存储commit和dispatch"
        },
        {
          "level": 2,
          "title": "vue  路由导航",
          "slug": "vue-路由导航"
        },
        {
          "level": 2,
          "title": "vue中computed和method 区别",
          "slug": "vue中computed和method-区别"
        }
      ]
    },
    {
      "title": "浅拷贝与深拷贝",
      "frontmatter": {},
      "regularPath": "/Components/javascript/clone.html",
      "relativePath": "Components/javascript/clone.md",
      "key": "v-553ac608",
      "path": "/Components/javascript/clone.html",
      "headers": [
        {
          "level": 2,
          "title": "1.对象的深拷贝",
          "slug": "_1-对象的深拷贝"
        },
        {
          "level": 2,
          "title": "2.数组的深拷贝方法",
          "slug": "_2-数组的深拷贝方法"
        },
        {
          "level": 2,
          "title": "3.多维数组实现深拷贝",
          "slug": "_3-多维数组实现深拷贝"
        }
      ]
    },
    {
      "title": "Web的缓存机制",
      "frontmatter": {},
      "regularPath": "/Components/performance/Browser.html",
      "relativePath": "Components/performance/Browser.md",
      "key": "v-3487cc0e",
      "path": "/Components/performance/Browser.html",
      "headers": [
        {
          "level": 2,
          "title": "Web的缓存机制",
          "slug": "web的缓存机制"
        },
        {
          "level": 2,
          "title": "As Total",
          "slug": "as-total"
        }
      ]
    },
    {
      "title": "WebWorker",
      "frontmatter": {},
      "regularPath": "/Components/performance/WebWorker.html",
      "relativePath": "Components/performance/WebWorker.md",
      "key": "v-bb20220c",
      "path": "/Components/performance/WebWorker.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/Components/md_interview/Interview.html",
      "relativePath": "Components/md_interview/Interview.md",
      "key": "v-f02bda70",
      "path": "/Components/md_interview/Interview.html"
    },
    {
      "title": "Button",
      "frontmatter": {},
      "regularPath": "/Components/static/Button.html",
      "relativePath": "Components/static/Button.md",
      "key": "v-7b1a1b00",
      "path": "/Components/static/Button.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        }
      ]
    },
    {
      "title": "初识React",
      "frontmatter": {},
      "regularPath": "/Components/react/base.html",
      "relativePath": "Components/react/base.md",
      "key": "v-c4d5817c",
      "path": "/Components/react/base.html",
      "headers": [
        {
          "level": 2,
          "title": "初识React",
          "slug": "初识react"
        },
        {
          "level": 3,
          "title": "特性：",
          "slug": "特性"
        },
        {
          "level": 3,
          "title": "React-Component",
          "slug": "react-component"
        },
        {
          "level": 3,
          "title": "组件的特点：",
          "slug": "组件的特点"
        },
        {
          "level": 3,
          "title": "React的优势",
          "slug": "react的优势"
        },
        {
          "level": 2,
          "title": "React的生命周期",
          "slug": "react的生命周期"
        }
      ]
    },
    {
      "title": "Icon",
      "frontmatter": {},
      "regularPath": "/Components/static/Icon.html",
      "relativePath": "Components/static/Icon.md",
      "key": "v-84328e1c",
      "path": "/Components/static/Icon.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        }
      ]
    },
    {
      "title": "放大镜",
      "frontmatter": {},
      "regularPath": "/Components/static/MagnifyingGlass.html",
      "relativePath": "Components/static/MagnifyingGlass.md",
      "key": "v-2e8f0328",
      "path": "/Components/static/MagnifyingGlass.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        }
      ]
    },
    {
      "title": "瀑布流",
      "frontmatter": {},
      "regularPath": "/Components/static/Pinterest.html",
      "relativePath": "Components/static/Pinterest.md",
      "key": "v-b35c4f70",
      "path": "/Components/static/Pinterest.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        }
      ]
    },
    {
      "title": "Button",
      "frontmatter": {},
      "regularPath": "/Components/static/Message.html",
      "relativePath": "Components/static/Message.md",
      "key": "v-4d070ab0",
      "path": "/Components/static/Message.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "API",
          "slug": "api"
        }
      ]
    },
    {
      "title": "滑块验证",
      "frontmatter": {},
      "regularPath": "/Components/static/SlideVerify.html",
      "relativePath": "Components/static/SlideVerify.md",
      "key": "v-1aced8c8",
      "path": "/Components/static/SlideVerify.html",
      "headers": [
        {
          "level": 2,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 2,
          "title": "Detail",
          "slug": "detail"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/Components/vue/base.html",
      "relativePath": "Components/vue/base.md",
      "key": "v-44a85ebc",
      "path": "/Components/vue/base.html",
      "headers": [
        {
          "level": 2,
          "title": "（1）什么是vue生命周期?",
          "slug": "_1-什么是vue生命周期"
        },
        {
          "level": 3,
          "title": "（2）vue生命周期的作用是什么?",
          "slug": "_2-vue生命周期的作用是什么"
        },
        {
          "level": 3,
          "title": "（3）vue生命周期总共有几个阶段?",
          "slug": "_3-vue生命周期总共有几个阶段"
        },
        {
          "level": 3,
          "title": "（4）第一次页面加载会触发哪几个钩子?",
          "slug": "_4-第一次页面加载会触发哪几个钩子"
        },
        {
          "level": 3,
          "title": "（5）DOM 渲染在 哪个周期中就已经完成?",
          "slug": "_5-dom-渲染在-哪个周期中就已经完成"
        },
        {
          "level": 3,
          "title": "（6）简单描述每个周期具体适合哪些场景?",
          "slug": "_6-简单描述每个周期具体适合哪些场景"
        },
        {
          "level": 2,
          "title": "axios的方法和请求响应数据结构",
          "slug": "axios的方法和请求响应数据结构"
        },
        {
          "level": 3,
          "title": "请求方法别名",
          "slug": "请求方法别名"
        },
        {
          "level": 3,
          "title": "相应数据结构",
          "slug": "相应数据结构"
        },
        {
          "level": 2,
          "title": "在VUE中封装axios",
          "slug": "在vue中封装axios"
        },
        {
          "level": 3,
          "title": "请求响应之then  catch",
          "slug": "请求响应之then-catch"
        },
        {
          "level": 2,
          "title": "Vuex状态管理",
          "slug": "vuex状态管理"
        },
        {
          "level": 2,
          "title": "VUE中router的钩子函数",
          "slug": "vue中router的钩子函数"
        },
        {
          "level": 2,
          "title": "ES6的基本知识",
          "slug": "es6的基本知识"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 2,
          "title": "vue store存储commit和dispatch",
          "slug": "vue-store存储commit和dispatch"
        },
        {
          "level": 2,
          "title": "vue  路由导航",
          "slug": "vue-路由导航"
        },
        {
          "level": 2,
          "title": "vue中computed和method 区别",
          "slug": "vue中computed和method-区别"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/Components/vue/template.html",
      "relativePath": "Components/vue/template.md",
      "key": "v-4bb298c2",
      "path": "/Components/vue/template.html",
      "headers": [
        {
          "level": 3,
          "title": "柯里化：一个函数可以接受多个参数，反复被调用",
          "slug": "柯里化-一个函数可以接受多个参数-反复被调用"
        },
        {
          "level": 3,
          "title": "需求：能实现ajax请求，自动在失败的时候重连，重试次数可传递，延迟时间",
          "slug": "需求-能实现ajax请求-自动在失败的时候重连-重试次数可传递-延迟时间"
        }
      ]
    },
    {
      "title": "一、数据驱动",
      "frontmatter": {},
      "regularPath": "/Components/vue/code.html",
      "relativePath": "Components/vue/code.md",
      "key": "v-acdf3fbc",
      "path": "/Components/vue/code.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": ""
        },
        {
          "level": 3,
          "title": "",
          "slug": "-2"
        },
        {
          "level": 2,
          "title": "五、如何让数据变得可观测？",
          "slug": "五、如何让数据变得可观测"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201805%2F19%2F20180519142022_kVASd.thumb.700_0.jpeg&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1664607012&t=d9c7f089d193df41489bad49ebf22dc3",
        "heroText": "karry的学习日记",
        "tagline": "没有跨不过去的坎，只有走不完的路",
        "actionText": "点击从这里开始",
        "actionLink": "/Components/base/introduce",
        "features": [
          {
            "title": "梦想-最开始的地方",
            "details": "活成自己最想活成的样子，加油！"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b12fbda",
      "path": "/"
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "logo": "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F201911%2F30%2F20191130103938_uNhF5.thumb.700_0.jpeg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1664606884&t=978883c3b180812cc76c793f1f6a6b92",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "JS",
        "link": "/Components/javascript/base"
      },
      {
        "text": "Vue",
        "link": "/Components/vue/bae"
      },
      {
        "text": "计算机网络知识",
        "link": "/Components/CpNet/base"
      },
      {
        "text": "面试总结",
        "link": "/Components/md_interview/interview"
      },
      {
        "text": "语言",
        "ariLabel": "2021",
        "items": [
          {
            "text": "中文",
            "link": "/language/chinese/"
          },
          {
            "text": "英文",
            "link": "/language/english/"
          }
        ]
      },
      {
        "text": "github",
        "link": ""
      }
    ],
    "sidebar": {
      "/Components/": [
        {
          "title": "开发指南",
          "collapsable": false,
          "children": [
            [
              "base/introduce",
              "介绍"
            ]
          ]
        },
        {
          "title": "HTML&CSS篇",
          "collapsable": false,
          "children": [
            [
              "htmlcss/Flex",
              "Flex布局"
            ],
            [
              "htmlcss/FontCss",
              "花式字体"
            ]
          ]
        },
        {
          "title": "Vue组件篇",
          "collapsable": false,
          "children": [
            [
              "static/Pinterest",
              "瀑布流"
            ],
            [
              "static/Icon",
              "图标"
            ],
            [
              "static/Button",
              "光亮按钮"
            ],
            [
              "static/Message",
              "信息提醒框"
            ],
            [
              "static/MagnifyingGlass",
              "放大镜效果"
            ],
            [
              "static/SlideVerify",
              "滑块验证"
            ]
          ]
        },
        {
          "title": "JavaScript篇",
          "collapsable": true,
          "children": [
            [
              "javascript/base",
              "JS基础"
            ],
            [
              "javascript/clone",
              "浅拷贝与深拷贝"
            ],
            [
              "javascript/ESsix",
              "ES6新拓展"
            ],
            [
              "javascript/extends",
              "JavaScript扩展"
            ],
            [
              "javascript/designPatterns",
              "JS常见设计模式"
            ]
          ]
        },
        {
          "title": "Vue篇",
          "collapsable": true,
          "children": [
            [
              "vue/base",
              "Vue基础"
            ],
            [
              "vue/code",
              "Vue源码分析"
            ]
          ]
        },
        {
          "title": "React篇",
          "collapsable": true,
          "children": [
            [
              "react/base",
              "初识React"
            ]
          ]
        },
        {
          "title": "NodeJS篇",
          "collapsable": true,
          "children": [
            [
              "NodeJs/Start",
              "初识NodeJS"
            ]
          ]
        },
        {
          "title": "Web性能提升篇",
          "collapsable": true,
          "children": [
            [
              "performance/Browser",
              "Web缓存"
            ],
            [
              "performance/WebWorker",
              "WebWorker"
            ]
          ]
        },
        {
          "title": "MiniPrograme篇",
          "collapsable": true,
          "children": [
            [
              "MiniPrograme/base",
              "初识小程序"
            ]
          ]
        },
        {
          "title": "Java基础篇",
          "collapsable": true,
          "children": []
        },
        {
          "title": "计算机网络知识篇",
          "collapsable": true,
          "children": [
            [
              "CpNet/base",
              "计算机网络基础"
            ]
          ]
        },
        {
          "title": "数据结构与算法篇",
          "collapsable": true,
          "children": [
            [
              "dataStructureAndCount/count",
              "算法"
            ]
          ]
        }
      ]
    }
  }
}